[files]
ignore-files = true
ignore-hidden = true
extend-exclude = [
    # not our typos
    "license.html",
    "jansu-sans-io/message",
]

[default]

[default.extend-words]
ser = "ser"
flate = "flate"
lso = "lso"
LSO = "LSO"
mis = "mis"
Ein = "Ein"
dbe = "dbe"
Hashi = "Hashi"
xdescribe = "xdescribe"
unparseable = "unparseable"
ure = "ure"
checksumed = "checksumed"
